services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    depends_on:
    - zookeeper
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://host.docker.internal:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  swift:
    build: .
    depends_on:
    - kafka
    ports:
      - "3000:3000"
    command: ["--server", "swift"]
    platform: "linux/amd64"
    environment:
      RUST_LOG: "kafka=debug,ws=debug"
      RUNNING_LOCAL: true
      ENDPOINT: "https://api.devnet.solana.com"
  
  swift-ws:
    build: .
    depends_on:
    - kafka
    ports:
    - "6969:6969"
    command: ["--server", "ws"]
    platform: "linux/amd64"
    environment:
      RUST_LOG: "info"
      RUNNING_LOCAL: true